#!/usr/bin/env bash

# colors

RESET='\e[0m'           # Reset
RED='\e[0;31m'          # Red
GREEN='\e[0;32m'        # Green
YELLOW='\e[0;33m'       # Yellow
BLUE='\e[0;34m'         # Blue
PURPLE='\e[0;35m'       # Magenta
CYAN='\e[0;36m'         # Cyan
WHITE='\e[0;37m'        # White
BRED='\e[1;31m'         # Bold Red
BGREEN='\e[1;32m'       # Bold Green
BYELLOW='\e[1;33m'      # Bold Yellow
BBLUE='\e[1;34m'        # Bold Blue
BPURPLE='\e[1;35m'      # Bold Magenta
BCYAN='\e[1;36m'        # Bold Cyan
BWHITE='\e[1;37m'       # Bold White

# variables
BEADLEDOM_VERSION="3.1"
ARCHETYPE_VERSION="3.1"
PACKAGE=
NAME=
GROUP_ID=
ARTIFACT_ID=
VERSION="1.0-SNAPSHOT"
MAVEN=`which mvn`

FINISHED=0

function display_usage() {
  printf "$GREEN      Usage:\n$RESET"
  printf "$GREEN        $0 new [generator-type] [flag(s)]\n$RESET"
  printf "$BGREEN                             User will be prompted for all options.\n$RESET"
  printf "$GREEN        Flags:\n\n$RESET"

  printf "$BGREEN            --help               ${GREEN}isplay this screen.\n\n$RESET"

  printf "$GREEN        Generators:\n\n$RESET"

  printf "$WHITE            simple-service ${GREEN}- Creates a skeleton Beadledom Service.\n$RESET"
  printf "$BGREEN                             Usage:\n$RESET"
  printf "$GREEN                                 $0 new simple-service\n$RESET"
}

function display_build() {
    cat <<EOM

        Create ${NAME} Beadledom Project with the following properties:

        Beadledom Version  ${BEADLEDOM_VERSION}
        Package            ${PACKAGE}
        Artifact Id        ${ARTIFACT_ID}
        Group Id           ${GROUP_ID}
        Version            ${VERSION}

        Does this look correct? [y/n/(q)uit]:

EOM
    read answer
    if [[ "$answer" == "y" || "$answer" == "Y" ]]; then
        FINISHED=1
    elif [[ $answer =~ ^[q|Q]*$ ]]; then
        exit 0
    else
        PACKAGE=""
        NAME=""
        FINISHED=0
    fi
}

function execute_archetype() {
    $MAVEN "archetype:generate" "-DinteractiveMode=false" "-DarchetypeGroupId=com.cerner.beadledom" "-DarchetypeArtifactId=simple-service" "-DarchetypeVersion=$ARCHETYPE_VERSION" "-DgroupId=$GROUP_ID" "-DartifactId=$ARTIFACT_ID" "-Dpackage=$PACKAGE" "-Dname=$NAME" "-Dversion=$VERSION" "-DbeadledomVersion=$BEADLEDOM_VERSION"
}


function get_params() {

    while [[ $FINISHED -eq 0 ]]; do

        echo "Please provide the following options or press enter to accept the default"
        echo "when available."
        echo; echo
        while [[ -z "$PACKAGE" ]]; do
            echo -e 'Package name (example: com.acme): '
            read PACKAGE
        done
        echo;

        while [[ -z "$NAME" ]]; do
            echo -e 'Project Name (example: AwesomeThing): '
            read NAME
            NAME="$(tr '[:lower:]' '[:upper:]' <<< ${NAME:0:1})${NAME:1}"
        done
        echo;

        # Set default ARTIFACT_ID based on the provided NAME. Example: SimpleService -> simple-service
        ARTIFACT_ID=$((sed 's/\(.\)\([A-Z]\)/\1-\2/g' | tr '[:upper:]' '[:lower:]') <<< $NAME)

        # Prompt for ARTIFACT_ID
        echo -e "Artifact Id [default: $ARTIFACT_ID] (example: awesome-thing): "
        read tmp

        # Override ARTIFACT_ID if user provided a value
        if [ -n "$tmp" ]; then
            ARTIFACT_ID="$tmp"
        fi

        # Set default GROUP_ID to the PACKAGE
        GROUP_ID=$PACKAGE
        # Prompt for GROUP_ID
        echo -e "Group Id [default: $GROUP_ID] (example: com.acme): "
        read tmp

        # Override GROUP_ID if user provided a value
        if [ -n "$tmp" ]; then
            GROUP_ID="$tmp"
        fi

        # Prompt for BEADLEDOM_VERSION
        echo -e "Beadledom version [default: $BEADLEDOM_VERSION]: "
        read tmp

        # Override BEADLEDOM_VERSION if user provided value
        if [ -n "$tmp" ]; then
            BEADLEDOM_VERSION="$tmp"
        fi

        display_build
    done

    execute_archetype
}

### End of function definitions

if [[ ( $1 == "--help") || $1 == "-h" ]]; then
    display_usage
    exit 0
elif [[ $1 == "new" ]]; then
    echo 'Creating new project.'
    echo; echo
    get_params
else
    display_usage
    exit 1
fi
